#!/bin/bash

# Run test for the server side application
mocha --compilers coffee:coffee-script --reporter spec server/test

# ..check if it pass
if [ $? -ne 0 ]; then
  echo "Failed!"
  exit 1
fi

# ..run other specs
grunt test
