#!/bin/bash

source ./script/lib/server
source ./script/lib/selenium

./script/xvfb start
startServer
startSelenium

grunt build:dev
grunt configureProxies connect:integration watch &
PID=$!

function isRunning() {
  nc -vz localhost 9001 &> /dev/null
}

echo -n "Waiting for the frontend server."
while ! isRunning; do
  echo -n "."
  sleep 0.1
done

echo -e "\nRunning integration specs."

protractor dev/test/protractor-conf.js --verbose --includeStackTrace

stopServer
stopSelenium
./script/xvfb stop

echo "Killing the frontend server PID=$PID"
kill "$PID"
